/* File generated by ExtractBody by Sandro Tolaini */

#define BODY_vx_logo_Width 410
#define BODY_vx_logo_Height 49
#define BODY_vx_logo_Depth 5
#define BODY_vx_logo_Masking 2
#define BODY_vx_logo_Transparent 0
#define BODY_vx_logo_Compression 1

extern unsigned long BODY_vx_logo_Colors[];

extern unsigned char BODY_vx_logo_Data[];
