/* C headerfile generated by RevUp 1.5 */

#define VERSION		2
#define REVISION	0
#define BETA	5
#define DATE	"10.1.04"
#define VERS	"VX 2.0 BETA 5"
#define VSTRING	"VX 2.0 BETA 5 (10.1.04)\r\n"
#define VERSTAG	"\0$VER: VX 2.0 BETA 5 (10.1.04)"
