/* C headerfile generated by RevUp 1.5 */

#define VERSION		1
#define REVISION	6
#define DATE	"24.1.2004"
#define VERS	"XProto 1.6"
#define VSTRING	"XProto 1.6 (24.1.2004)\r\n"
#define VERSTAG	"\0$VER: XProto 1.6 (24.1.2004)"
